# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-social-card-2',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-social-card-2',
                'lib_path': 'test_social_card_2'},
  'syms': {'test_social_card_2.core': {'test_social_card_2.core.foo': ('core.html#foo', 'test_social_card_2/core.py')}}}
